ERROR - 2023-12-09 13:51:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'ppks', 3306, '', 0)
#1 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\TugasPBL\PBLS3\app\Models\GaleriModel.php(46): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\TugasPBL\PBLS3\app\Controllers\BerandaController.php(30): App\Models\GaleriModel->GetDataGaleriRandom()
#6 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(919): App\Controllers\BerandaController->beranda()
#7 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BerandaController))
#8 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\TugasPBL\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\TugasPBL\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\TugasPBL\PBLS3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\TugasPBL\PBLS3\app\Models\GaleriModel.php(46): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\TugasPBL\PBLS3\app\Controllers\BerandaController.php(30): App\Models\GaleriModel->GetDataGaleriRandom()
#5 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(919): App\Controllers\BerandaController->beranda()
#6 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BerandaController))
#7 C:\xampp\htdocs\TugasPBL\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\TugasPBL\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\TugasPBL\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-12-09 13:51:49 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `galeri`
ORDER BY RAND()
 LIMIT 3', [], false)
 3 APPPATH\Models\GaleriModel.php(46): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\BerandaController.php(30): App\Models\GaleriModel->GetDataGaleriRandom()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\BerandaController->beranda()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BerandaController))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 14:55:10 --> Undefined variable $request
in APPPATH\Controllers\Pengaduan.php on line 11.
 1 APPPATH\Controllers\Pengaduan.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', 'C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\app\\Controllers\\Pengaduan.php', 11)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 14:56:12 --> Undefined property: App\Controllers\Pengaduan::$input
in APPPATH\Controllers\Pengaduan.php on line 11.
 1 APPPATH\Controllers\Pengaduan.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Pengaduan::$input', 'C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\app\\Controllers\\Pengaduan.php', 11)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:47:41 --> Allowed fields must be specified for model: "App\Models\PengaduanModel"
in SYSTEMPATH\Model.php on line 736.
 1 SYSTEMPATH\Model.php(736): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\PengaduanModel')
 2 SYSTEMPATH\BaseModel.php(763): CodeIgniter\Model->doProtectFieldsForInsert([...])
 3 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Pengaduan.php(106): CodeIgniter\Model->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:48:13 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 768.
 1 SYSTEMPATH\BaseModel.php(768): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Pengaduan.php(106): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:48:13 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 768.
 1 SYSTEMPATH\BaseModel.php(768): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Pengaduan.php(106): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:49:21 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 768.
 1 SYSTEMPATH\BaseModel.php(768): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Pengaduan.php(106): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:51:02 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 768.
 1 SYSTEMPATH\BaseModel.php(768): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Pengaduan.php(108): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\TugasPBL\\PBLS3\\public\\index.php')
CRITICAL - 2023-12-09 15:05:45 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 768.
 1 SYSTEMPATH\BaseModel.php(768): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([], true)
 3 APPPATH\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PBLS3\\public\\index.php')
ERROR - 2023-12-09 15:06:24 --> mysqli_sql_exception: Unknown column 'siapa' in 'field list' in C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\PBLS3\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\PBLS3\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PBLS3\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PBLS3\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\PBLS3\app\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
#9 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#10 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-12-09 15:06:24 --> Unknown column 'siapa' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pengaduan` (`siapa`, `tanggal_dibuat`, `updated_at`) VALUES (:siapa:, :tanggal_dibuat:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PBLS3\\public\\index.php')
ERROR - 2023-12-09 15:07:06 --> mysqli_sql_exception: Unknown column 'siapa' in 'field list' in C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\PBLS3\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\PBLS3\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PBLS3\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PBLS3\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\PBLS3\app\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
#9 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#10 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-12-09 15:07:06 --> Unknown column 'siapa' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pengaduan` (`siapa`, `tanggal_dibuat`, `updated_at`) VALUES (:siapa:, :tanggal_dibuat:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PBLS3\\public\\index.php')
ERROR - 2023-12-09 15:07:38 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\PBLS3\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\PBLS3\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PBLS3\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PBLS3\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\PBLS3\app\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
#9 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#10 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-12-09 15:07:38 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pengaduan` (`siapa`, `tanggal_dibuat`, `updated_at`) VALUES (:siapa:, :tanggal_dibuat:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PBLS3\\public\\index.php')
ERROR - 2023-12-09 15:08:04 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\PBLS3\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `pe...', 0)
#1 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pe...')
#2 C:\xampp\htdocs\PBLS3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pe...')
#3 C:\xampp\htdocs\PBLS3\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\PBLS3\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PBLS3\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PBLS3\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\PBLS3\app\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
#9 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
#10 C:\xampp\htdocs\PBLS3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\PBLS3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\PBLS3\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-12-09 15:08:04 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pengaduan` (`siapa`, `tanggal_dibuat`, `updated_at`) VALUES (:siapa:, :tanggal_dibuat:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Pengaduan.php(107): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Pengaduan->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pengaduan))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\PBLS3\\public\\index.php')
